name: base
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_hooks: ^0.20.5
  logging: ^1.1.1
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1
  connectivity_plus: ^6.0.3
  gap: ^3.0.0
  go_router: ^14.0.2
  intl: any
  get_it: ^7.6.0
  envied: ^0.5.4+1
  dio: ^5.2.1+1
  extended_image: ^8.1.0
  uuid: ^4.4.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen_runner: ^5.3.1
  riverpod_generator: ^2.2.1
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  build_runner: ^2.4.5
  change_app_package_name: ^1.1.0
  test: ^1.24.9
  envied_generator: ^0.5.2
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/

flutter_gen:
  assets:
    enabled: true
    outputs:
      class_name: MyAssets
  #      package_parameter_enabled: true
  fonts:
    enabled: true
    outputs:
      class_name: MyFontFamily
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true
